//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDataLatest
    {
        public int id { get; set; }
        public string Fullname { get; set; }
        public string Department { get; set; }
        public string Email { get; set; }
        public string Ippis { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public string Comment { get; set; }
        public string role { get; set; }
    }
}
