//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Supplier
    {
        public System.Guid id { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string ContactTitle { get; set; }
        public string Address { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Region { get; set; }
        public string Phone { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.Guid> CreatedUser { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.Guid SupplierId { get; set; }
        public string ActivityStatus { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
