//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_CompanyStockTag
    {
        public System.Guid id { get; set; }
        public string Stockname { get; set; }
        public decimal CompanyPrice { get; set; }
        public System.DateTime Setdate { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> CreatedUser { get; set; }
        public string ActivityStatus { get; set; }
        public Nullable<System.Guid> CompanyStockTagId { get; set; }
    
        public virtual CompanyStockTag CompanyStockTag { get; set; }
    }
}
