//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldAgent
    {
        public System.Guid id { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Othernames { get; set; }
        public System.Guid GenderId { get; set; }
        public string AllocatedZone { get; set; }
        public string Remark { get; set; }
        public bool Status { get; set; }
        public int CountryId { get; set; }
        public int StateId { get; set; }
        public Nullable<System.Guid> CreatedUser { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
