//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Audit_CurrentStock
    {
        public System.Guid id { get; set; }
        public System.Guid StocknameId { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public string PackUnit { get; set; }
        public decimal SupplierUnitPrice { get; set; }
        public Nullable<decimal> CompanyUnitPrice { get; set; }
        public Nullable<System.Guid> CreatedUser { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string Comment { get; set; }
    }
}
