//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.Sales = new HashSet<Sale>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid AgentId { get; set; }
        public System.Guid CustomerId { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<bool> Pending { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public decimal TotalOrderAmount { get; set; }
        public decimal TotalSuppliedAmount { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string PaymentType { get; set; }
        public string OrderTag { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        public virtual FieldAgent FieldAgent { get; set; }
    }
}
