//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public System.Guid id { get; set; }
        public System.Guid ProductId { get; set; }
        public int Quantity { get; set; }
        public decimal SalesUnitPrice { get; set; }
        public decimal SalesTotalAmount { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public string BatchNo { get; set; }
        public decimal SuppliedUnitPrice { get; set; }
        public decimal SuppliedTotalPrice { get; set; }
        public System.Guid AgentId { get; set; }
    
        public virtual CompanyStockTag CompanyStockTag { get; set; }
        public virtual Order Order { get; set; }
    }
}
