//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleReport
    {
        public System.Guid id { get; set; }
        public System.Guid SaleId { get; set; }
        public decimal AmountCollected { get; set; }
        public decimal SuppliedAmount { get; set; }
        public decimal ProfitMade { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
